import React from 'react'

const Head = () => {
  return (
    <>
       <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <meta
            name="description"
            content="Generated by create next app"
        />
       <link rel="icon" href="/favicon.icon"></link>
    </>
  )
}

export default Head;